### PR TITLE
Consider all HTTPProxy route services

### LINKED ISSUE #15: Unable to find service in HTTPProxy with more than one route
**Describe the bug**

When trying to set the weight of an HTTPProxy with more than one route, it is only able to find the services of the first route:

```
'TrafficRoutingError' failed to set weight via plugin: the service: api-canary is not found in HTTPProxy
```

**To Reproduce**

Create an HTTPProxy with more than one route, and try to set the weight of the second route.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app
spec:
  virtualhost:
    fqdn: example.com
    tls:
      secretName: ingress
  routes:
    - conditions:
        - prefix: /
      services:
        - name: web
          port: 80
        - name: web-canary
          port: 80
    - conditions:
        - prefix: /api
      services:
        - name: api
          port: 80
        - name: api-canary
          port: 80
```

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
spec:
  strategy:
    canary:
      canaryService: api-canary
      stableService: api
      trafficRouting:
        plugins:
          argoproj-labs/contour:
            namespace: api
            httpProxy: api
```

**Version**
```
argoproj/argo-rollouts:v1.5.0
argoproj-labs/rollouts-plugin-trafficrouter-contour:v0.1.1
```

### PR DESCRIPTION
**Pull request by mvgmb**
Closes #15

### CODE REVIEW

**Comment by wilsonwu** [comment]
@izturn could you please help to review, thanks!

**Comment by izturn** [comment]
@mvgmb  thx,  i will review it later

File: pkg/plugin/plugin.go [hunk 1]
```diff
@@ -86,9 +86,8 @@ func (r *RpcPlugin) SetWeight(
 	slog.Debug("the services name", slog.String("stable", stableSvcName), slog.String("canary", canarySvcName))
 
 	// TODO: filter by condition(s)
-	services := utils.Must1(getServiceList(httpProxy.Spec.Routes))
-	canarySvc := utils.Must1(getService(canarySvcName, services))
-	stableSvc := utils.Must1(getService(stableSvcName, services))
+	canarySvc := utils.Must1(getService(canarySvcName, &httpProxy))
```
Comment (izturn) [inline pkg/plugin/plugin.go:89]: if you like remove the `getServiceList`, then search the `canaryService & stableService` at the same time , maybe better?

**Review by izturn — COMMENTED** [review]
f you like remove the getServiceList, then search the canaryService & stableService at the same time , maybe better?

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (mvgmb) [reply pkg/plugin/plugin.go]: Instead of removing the `getServiceList`, I modified it to return a map instead of a list to avoid iterating over the HTTPProxy's service list.

**Comment by izturn** [comment]
LGTM pls fix the conflicts first

**Review by izturn — APPROVED** [review]
thx
